* Package ‘tibbletime’
* January 30, 2018
* Type Package
* Title Time Aware Tibbles
* Version 0.1.1
* Date 2018-01-29
* Maintainer Davis Vaughan <dvaughan@business-science.io>

#### Description 
Built on top of the 'tibble' package, 'tibbletime' is an extension that allows for the creation of time aware tibbles. Some immediate
advantages of this include: the ability to perform time-based subsetting on tibbles, quickly summarising and aggregating results by time periods, and creating columns that can be used as 'dplyr' time-based groups.

* URL https://github.com/business-science/tibbletime
* BugReports https://github.com/business-science/tibbletime/issues
* License MIT + file LICENSE
* Encoding UTF-8

Suggests broom, covr, gapminder, knitr, testthat, tidyr
RoxygenNote 6.0.1
Depends R (>= 3.2.0)
Imports assertthat (>= 0.2.0), dplyr (>= 0.7.4), glue (>= 1.1.1), hms
(>= 0.4), lubridate (>= 1.6.0), purrr (>= 0.2.3), rlang (>=
0.1.6), tibble (>= 1.4.1), Rcpp (>= 0.12.7), zoo (>= 1.8-0)
VignetteBuilder knitr
LinkingTo Rcpp
NeedsCompilation yes
Author Davis Vaughan [aut, cre],
Matt Dancho [aut]
Repository CRAN
Date/Publication 2018-01-30 15:51:52 UTC

##### R topics documented:
as_period . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
as_tbl_time . . . . . . . . . . . . . . . .  . . . . . . . . . . . 5
ceiling_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
collapse_by . . . . . . . .  . . . . . . . . . . . . . . . . . 7
collapse_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
create_series . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
FANG . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
FB . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
filter_time . . . . . . . . . . . . . . . . . . . . . . . . . 13
floor_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
getters . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
parse_period . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
partition_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
posixct_numeric_to_datetime . . . . . . . . . . . . . . . 18
reconstruct . . . . . . . . . . . . . .  . . . . . . . . . . . . . . . . . . . . 19
rollify . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
tibbletime . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22
Index 23
