Package ‘tibbletime’
January 30, 2018
Type Package
Title Time Aware Tibbles
Version 0.1.1
Date 2018-01-29
Maintainer Davis Vaughan <dvaughan@business-science.io>
Description Built on top of the 'tibble' package, 'tibbletime' is an extension
that allows for the creation of time aware tibbles. Some immediate
advantages of this include: the ability to perform time-based subsetting
on tibbles, quickly summarising and aggregating results by time periods,
and creating columns that can be used as 'dplyr' time-based groups.
URL https://github.com/business-science/tibbletime
BugReports https://github.com/business-science/tibbletime/issues
License MIT + file LICENSE
Encoding UTF-8
Suggests broom, covr, gapminder, knitr, testthat, tidyr
RoxygenNote 6.0.1
Depends R (>= 3.2.0)
Imports assertthat (>= 0.2.0), dplyr (>= 0.7.4), glue (>= 1.1.1), hms
(>= 0.4), lubridate (>= 1.6.0), purrr (>= 0.2.3), rlang (>=
0.1.6), tibble (>= 1.4.1), Rcpp (>= 0.12.7), zoo (>= 1.8-0)
VignetteBuilder knitr
LinkingTo Rcpp
NeedsCompilation yes
Author Davis Vaughan [aut, cre],
Matt Dancho [aut]
Repository CRAN
Date/Publication 2018-01-30 15:51:52 UTC
1
2 as_period
R topics documented:
as_period . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
as_tbl_time . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
ceiling_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
collapse_by . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
collapse_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
create_series . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
FANG . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
FB . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
filter_time . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
floor_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
getters . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
parse_period . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
partition_index . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
posixct_numeric_to_datetime . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
reconstruct . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
rollify . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
tibbletime . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22
Index 23
as_period Change tbl_time periodicity
Description
Convert a tbl_time object from daily to monthly, from minute data to hourly, and more. This
allows the user to easily aggregate data to a less granular level by taking the value from either the
beginning or end of the period.
Usage
as_period(.tbl_time, period = "yearly", start_date = NULL, side = "start",
include_endpoints = FALSE, ...)
Arguments
.tbl_time A tbl_time object.
period A character specification used for time-based grouping. The general format to
use is "frequency period" where frequency is a number like 1 or 2, and period
is an interval like weekly or yearly. There must be a space between the two.
Note that you can pass the specification in a flexible way:
• 1 Year: '1 year' / '1 Y' / '1 yearly' / 'yearly'
This shorthand is available for year, quarter, month, day, hour, minute, second,
millisecond and microsecond periodicities.
Additionally, you have the option of passing in a vector of dates to use as custom
and more flexible boundaries.
as_period 3
start_date Optional argument used to specify the start date for the first group. The default
is to start at the closest period boundary below the minimum date in the supplied
index.
side Whether to return the date at the beginning or the end of the new period. By
default, the "start" of the period. Use "end" to change to the end of the period.
include_endpoints
Whether to include the first or last data point in addition to the transformed data.
... Not currently used.
Details
This function respects dplyr::group_by() groups.
The side argument is useful when you want to return data at, say, the end of a quarter, or the end
of a month.
include_endpoints can be useful when calculating a change over time. In addition to changing to
monthly dates, you often need the first data point as a baseline for the first calculation.
Examples
# Basic usage ---------------------------------------------------------------
# FB stock prices
data(FB)
FB <- as_tbl_time(FB, date)
# Aggregate FB to yearly data
as_period(FB, "yearly")
# Aggregate FB to every 2 years
as_period(FB, "2 years")
# Aggregate FB to yearly data, but use the last data point available
# in that period
as_period(FB, "yearly", side = "end")
# Aggregate FB to yearly data, end of period, and include the first
# endpoint
as_period(FB, "yearly", side = "end", include_endpoints = TRUE)
# Aggregate to weekly. Notice that it only uses the earliest day available
# in the data set at that periodicity. It will not set the date of the first
# row to 2013-01-01 because that date did not exist in the original data set.
as_period(FB, "weekly")
# Aggregate to every other week
as_period(FB, "2 weeks")
# FB is daily data, aggregate to minute?
# Not allowed for Date class indices, an error is thrown
4 as_period
# as_period(FB, "minute")
# Grouped usage -------------------------------------------------------------
# FANG contains Facebook, Amazon, Netflix and Google stock prices
data(FANG)
FANG <- as_tbl_time(FANG, date)
FANG <- dplyr::group_by(FANG, symbol)
# Respects groups
as_period(FANG, "yearly")
# Every 6 months, respecting groups
as_period(FANG, "6 months")
# Using start_date ----------------------------------------------------------
#### One method using start_date
# FB stock prices
data(FB)
FB <- as_tbl_time(FB, date)
# The Facebook series starts at 2013-01-02 so the 'every 2 day' counter
# starts at that date as well. Groups become (2013-01-02, 2013-01-03),
# (2013-01-04, 2013-01-05) and so on.
as_period(FB, "2 day")
# Specifying the `start_date = "2013-01-01"` might be preferable.
# Groups become (2013-01-01, 2013-01-02), (2013-01-03, 2013-01-04) and so on.
as_period(FB, "2 day", start_date = "2013-01-01")
#### Equivalent method using an index vector
# FB stock prices
data(FB)
FB <- as_tbl_time(FB, date)
custom_period <- create_series(
time_formula = dplyr::first(FB$date) - 1 ~ dplyr::last(FB$date),
period = "2 day",
class = "Date",
as_vector = TRUE)
FB %>%
as_tbl_time(date) %>%
as_period(period = custom_period)
# Manually calculating returns at different periods -------------------------
data(FB)
as_tbl_time 5
# Annual Returns
# Convert to end of year periodicity, but include the endpoints to use as
# a reference for the first return calculation. Then calculate returns.
FB %>%
as_tbl_time(date) %>%
as_period("1 y", side = "end", include_endpoints = TRUE) %>%
dplyr::mutate(yearly_return = adjusted / dplyr::lag(adjusted) - 1)
as_tbl_time Create tbl_time objects
Description
tbl_time objects have a time index that contains information about which column should be used
for time-based subsetting and other time-based manipulation. Otherwise, they function as normal
tibbles.
Usage
as_tbl_time(x, index = NULL, ...)
tbl_time(x, index = NULL)
Arguments
x An object to be converted to tbl_time. This is generally a tibble::tibble(),
or an object that can first be coerced to a tibble.
index The bare column name of the column to be used as the index.
... Arguments passed to tibble::as_tibble() if coercion is necessary first.
Details
The information stored about tbl_time objects are the index_quo and the index_time_zone.
These are stored as attributes, with the index_quo as a rlang::quosure() and the time_zone as
a string.
Currently, Date and POSIXct classes are fully supported. yearmon, yearqtr, and hms have experimental
support. Due to dplyr’s handling of S3 classes like these 3, the classes are lost when you
manipulate the index columns directly.
Examples
# Converting a data.frame to a `tbl_time`
# Using Date index
ex1 <- data.frame(date = Sys.Date(), value = 1)
ex1_tbl_time <- as_tbl_time(ex1, date)
6 ceiling_index
class(ex1_tbl_time)
attributes(ex1_tbl_time)
# Converting a tibble to a `tbl_time`
# Using POSIXct index
ex2 <- tibble::tibble(
time = as.POSIXct(c("2017-01-01 10:12:01", "2017-01-02 12:12:01")),
value = c(1, 2)
)
as_tbl_time(ex2, time)
ceiling_index A simple wrapper of lubridate::ceiling_date()
Description
This is a thin wrapper around a lubridate::ceiling_date() that works for hms, yearmon, and
yearqtr classes as well.
Usage
ceiling_index(x, unit = "seconds")
Arguments
x a vector of date-time objects
unit a character string specifying a time unit or a multiple of a unit to be rounded
to. Valid base units are second, minute, hour, day, week, month, bimonth,
quarter, season, halfyear and year. Arbitrary unique English abbreviations
as in the period() constructor are allowed. Rounding to multiple of units (except
weeks) is supported.
See Also
lubridate::ceiling_date()
Examples
data(FB)
dplyr::mutate(FB, date2 = ceiling_index(date, "year"))
time_test <- create_series('00:00:00'~'12:00:00',
'1 minute', class = "hms")
dplyr::mutate(time_test, date2 = ceiling_index(date, "hour"))
